Add permission for READ_WALLPAPER_INTERNAL
- Currently having following issue causing bootloop:
java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.wallpaper (/system_ext/priv-app/StatixThemePicker): android.permission.READ_WALLPAPER_INTERNAL}