[WIP] StatixThemePicker: Update to UP1A.231005.007
TODO:
- Fix the following error:
StatixCustomizationInjector.kt:38:34: error: cannot access 'getNotificationInteractor': it is invisible (private in a supertype) in 'StatixCustomizationInjector'
- Update recent provider

Change-Id: Id16b444b6397219ad30c29161a9e1d9a4c16d8fe